baseURL = "https://xn--blaufusstlpel-qmb.de/"
theme = ["projektemacher-base", "parsa"]
title = "Blaufußtölpel"
languageCode = "de"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
paginate = 6
#disableKinds = ["taxonomy"]
#ignoreErrors = ["error-disable-taxonomy"]

# navigation
[menu]
    [[menu.main]]
        name = "Zeitstrahl"
        URL = "/timeline"
        weight = 1

    [[menu.main]]
        name = "Links"
        URL = "/links"
        weight = 2

    [[menu.main]]
        name = "Über"
        URL = "/about"
        weight = 3

[markup.goldmark.renderer]
  unsafe= true

[imaging]
    quality = 95

#[outputs]
#    page = ["HTML", "JSON"]

[mediaTypes]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]

# See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

[module]

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

  [[module.mounts]]
    source = "node_modules/slick-carousel/slick/fonts/"
    target = "static/fonts/slick"

  [[module.mounts]]
    source = "node_modules/slick-carousel/slick/ajax-loader.gif"
    target = "static/images/ajax-loader.gif"

  [[module.mounts]]
    source = "themes/parsa/assets/css"
    target = "assets/css"

  [[module.mounts]]
    source = "static"
    target = "static"
