baseURL = "https://xn--blaufusstlpel-qmb.de/"
theme = "parsa"
title = "Blaufußtölpel"
languageCode = "de"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
paginate = 6
#disableKinds = ["taxonomy"]
#ignoreErrors = ["error-disable-taxonomy"]

[params]
    layout = "1"
    logo = "images/blaufusstoelpel.svg"
    header = "images/header.svg"
# font https://fonts.google.com/specimen/Prata body
# https://fonts.google.com/specimen/Montserrat head
    iiifCanvasHeight = 400
    iiifCanvasWidth = 300
    productionIIIFURLPrefix="https://static.projektemacher.org/blaufusstoelpel/"
    errorimg = "images/blaufusstoelpel.svg"
    copyright = "MMXX"

# navigation
[menu]
    [[menu.main]]
        name = "Zeitstrahl"
        URL = "timeline"
        weight = 1

    [[menu.main]]
        name = "Über"
        URL = "about"
        weight = 2

[markup.goldmark.renderer]
  unsafe= true

[imaging]
    quality = 95

[outputs]
    page = ["HTML", "JSON"]

[module]

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

  [[module.mounts]]
    source = "node_modules/slick-carousel/slick/fonts/"
    target = "static/fonts/slick"

  [[module.mounts]]
    source = "node_modules/slick-carousel/slick/ajax-loader.gif"
    target = "static/images/ajax-loader.gif"

  [[module.mounts]]
    source = "static"
    target = "static"
