baseURL = "https://xn--blaufusstlpel-qmb.de/"
theme = ["projektemacher-base", "parsa"]
title = "Blaufußtölpel"
languageCode = "de"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
#paginate = 6
#disableKinds = ["taxonomy"]
#ignoreErrors = ["error-disable-taxonomy"]
timeout = 60
enableGitInfo = true
enableRobotsTXT = true

[pagination]
  pagerSize = 6

# navigation
[menu]
  [[menu.main]]
    name = "Zeitstrahl"
    URL = "/timeline"
    weight = 1

  [[menu.main]]
    name = "Links"
    URL = "/links"
    weight = 2

  [[menu.main]]
    name = "Über"
    URL = "/about"
    weight = 3

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

    [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
            enable = true
        [markup.goldmark.extensions.extras.mark]
            enable = true
        [markup.goldmark.extensions.extras.subscript]
            enable = true
        [markup.goldmark.extensions.extras.superscript]
            enable = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

[imaging]
    quality = 95

#[outputs]
#    page = ["HTML", "JSON"]

[mediaTypes]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]

# See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-manifest]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-collection]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "collection"
    notAlternative = true

[sitemap]
  changeFreq = 'weekly'

[module]

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

  [[module.mounts]]
    source = "node_modules/slick-carousel/slick/fonts/"
    target = "static/fonts/slick"

  [[module.mounts]]
    source = "node_modules/slick-carousel/slick/ajax-loader.gif"
    target = "static/images/ajax-loader.gif"

  [[module.mounts]]
    source = "themes/parsa/assets/css"
    target = "assets/css"

  [[module.mounts]]
    source = "static"
    target = "static"

[build]
  writeStats = true

[[cascade]]
  outputs = ['html','rss', 'iiif-collection']
  [cascade._target]
    kind = "term"

[security]
  [security.http]
    mediaTypes = ['^application/json$', '^application/json;\s?charset=[uU][tT][fF]-8$', '^application/sparql-results\+json;\s?charset=[uU][tT][fF]-8$']
