baseURL = "https://xn--blaufusstlpel-qmb.de"
theme = "parsa"
title = "Blaufußtölpel"
languageCode = "de"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true

[params]
layout = "1"
#logo = "images/blaufusstoelpel.svg"
# font https://fonts.google.com/specimen/Prata body
# https://fonts.google.com/specimen/Montserrat head


# navigation
[menu]
    [[menu.main]]
    name = "Über"
    URL = "about"
    weight = 2

    [[menu.main]]
    name = "Kontakt"
    URL = "contact"
    weight = 3


[markup.goldmark.renderer]
  unsafe= true

[imaging]
    quality = 95

[module]

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"
